### PR TITLE
collect PyPy 3.10 dlls

### PR DESCRIPTION
**Pull request by davidhewitt**
Noticed that we haven't yet got this after trying to update a project to PyO3 0.19.1. 😬

### CODE REVIEW

**Comment by davidhewitt** [comment]
Thanks for the quick merge (and follow-ups)!

**Comment by ravenexp** [comment]
I'm going to release v0.2.8 right now.

**Comment by davidhewitt** [comment]
Thanks for the fast turnaround 🚀

**Comment by messense** [comment]
https://github.com/PyO3/python3-dll-a/blob/66b55071fae571f0760211ff065ab411f65af376/src/lib.rs#L264

Need to add PyPy 3.10 to here too.

**Pull request merged**
